name: llm
channels:
  - conda-forge
dependencies:
  - python=3.11

  # dev packages
  - autoflake>=1.7.5
  - epc>=0.0.5
  - pandas-stubs
  - ptvsd>=4.3.2

  # lsp deps
  - pylsp-mypy>=0.6.8  # currently using anaconda-mode however

  - pip
  - pip:
    - axelrod
    - gdm-concordia

    # dev packages
    - importmagic>=0.1.7
    - ipywidgets
